services:
  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - "8081:8081"
    networks:
      - technova-net

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8082:8082"
    environment:
      - INVENTORY_SERVICE_URL=http://inventory-service:8081
    depends_on:
      - inventory-service
    networks:
      - technova-net

  prometheus:
    build: ./monitoring/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - technova-net

  grafana:
    build: ./monitoring/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki
    networks:
      - technova-net

  loki:
    build: ./monitoring/loki
    container_name: loki
    ports:
      - "3100:3100"
    networks:
      - technova-net

  promtail:
    build: ./monitoring/promtail
    container_name: promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - loki
    networks:
      - technova-net

networks:
  technova-net:
    driver: bridge