# TechNova Inventory - konfigurasi SonarScanner untuk kedua microservices
sonar.projectKey=technova-inventory
sonar.projectName=TechNova Inventory Management

# Scan kedua folder service, exclude vendor & data
sonar.sources=inventory-service/src,inventory-service/public,order-service/src,order-service/public
sonar.tests=inventory-service/tests,order-service/tests
sonar.exclusions=**/vendor/**,**/data/**

sonar.sourceEncoding=UTF-8
